input {
  beats {
    port => 5044
  }
}

filter {

  if "ICMP" in [message] {
    mutate {
      add_field => { "traffic_type" => "PING" }
    }
  }

  if "SSH" in [message] {
    mutate {
      add_field => { "traffic_type" => "SSH" }
    }
  }

  if "phpMyAdmin" in [message] {
    mutate {
      add_field => { "traffic_type" => "PHPMYADMIN" }
    }
  }

}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "snort-events"
  }
}
